name: multipass
title: Multipass
icon: data/multipass.gui.svg
summary: Instant Ubuntu VMs
description: |
  Multipass is a tool to launch and manage VMs on Windows, Mac and Linux that
  simulates a cloud environment with support for cloud-init. Get Ubuntu
  on-demand with clean integration to your IDE and version control on your
  native platform.
license: GPL-3.0

adopt-info: multipass
confinement: strict
base: core20

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qemu:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qemu

plugs:
  all-home:
    interface: home
    read: all

apps:
  multipassd:
    command: bin/launch-multipassd
    environment:
      LD_LIBRARY_PATH: &library-path
        $SNAP/lib:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
      PATH: &path
        $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
      QT_PLUGIN_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins
      XDG_DATA_HOME: $SNAP_COMMON/data
      XDG_CACHE_HOME: $SNAP_COMMON/cache
      XDG_CONFIG_HOME: &daemon-config $SNAP_DATA/config
      DAEMON_CONFIG_HOME: *daemon-config # temporary
    daemon: simple
    plugs:
      - all-home
      - firewall-control
      - kvm
      - libvirt
      - multipass-support
      - network-bind
      - network-control
      - network-manager # for bridge creation
      - lxd
      - removable-media
  multipass:
    environment:
      <<: &client-environment
        LD_LIBRARY_PATH: *library-path
        PATH: *path
        QT_PLUGIN_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins
        XDG_DATA_HOME: $SNAP_USER_DATA/data
        XDG_DATA_DIRS: $SNAP/usr/share
        XDG_CACHE_HOME: $SNAP_USER_DATA/cache
        XDG_CONFIG_HOME: $SNAP_USER_DATA/config
      DAEMON_CONFIG_HOME: *daemon-config # temporary
    command: bin/launch-multipass
    completer: etc/bash_completion.d/snap.multipass
    plugs:
      - all-home
      - network
  gui:
    environment: *client-environment
    command: bin/launch-multipass-gui
    desktop: usr/share/applications/multipass.gui.desktop
    autostart: multipass.gui.autostart.desktop
    plugs:
      - home
      - network
      - unity7
      - wayland
      - x11

parts:
  multipass:
    plugin: cmake
    build-snaps:
    - cmake
    build-environment:
    - PATH: /snap/bin:$PATH
    build-packages:
    - on arm64: [libgles2-mesa-dev]
    - on armhf: [libgles2-mesa-dev]
    - build-essential
    - git
    - libapparmor-dev
    - libqt5x11extras5-dev
    - libsystemd-dev
    - libssl-dev
    - libvirt-dev
    - pkg-config
    - qtbase5-dev
    - qtbase5-dev-tools
    stage-packages:
    - apparmor
    - on amd64: [libgl1]
    - on armhf: [libgles2-mesa]
    - on arm64: [libgles2-mesa]
    - libpng16-16
    - libqt5core5a
    - libqt5gui5
    - libqt5network5
    - libqt5widgets5
    - libqt5x11extras5
    - libssl1.1
    - libxml2
    - libvirt0
    - dnsmasq-base
    - dnsmasq-utils
    source: .
    cmake-parameters:
    - -DCMAKE_BUILD_TYPE=RelWithDebInfo
    - -DCMAKE_INSTALL_PREFIX=/
    - -DMULTIPASS_ENABLE_TESTS=off
    - -DMULTIPASS_UPSTREAM=origin
    override-build: |
      snapcraftctl build
      set -e
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/etc/bash_completion.d/
      echo 'export PATH="${PATH}:/snap/bin:/var/lib/snapd/snap/bin"' > ${SNAPCRAFT_PART_INSTALL}/etc/bash_completion.d/snap.multipass
      cat ../src/completions/bash/multipass >> ${SNAPCRAFT_PART_INSTALL}/etc/bash_completion.d/snap.multipass
      VERSION=$( awk -F\" '/version_string/ { print $2 }' gen/multipass/version.h )
      snapcraftctl set-version ${VERSION}
      snapcraftctl set-grade $( echo ${VERSION} | grep -qe '^[0-9]\+\.[0-9]\+\.[0-9]\+\($\|-rc\)' && echo stable || echo devel )
      sed -i -e 's@^Icon=\(.\+\)$@Icon=/usr/share/icons/hicolor/scalable/apps/\1.svg@' ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/multipass.gui.desktop

      cd ${SNAPCRAFT_PART_SRC}/3rd-party
      find . -name 'LICENSE*' -print0 | xargs -0 -I FILE install --mode=644 -D --no-target-directory FILE ${SNAPCRAFT_PART_INSTALL}/licenses/FILE

  qemu:
    plugin: nil
    override-pull: ""
    stage-packages:
    - ipxe-qemu-256k-compat-efi-roms
    - on amd64: [qemu-system-x86]
    - on armhf: [qemu-system-arm]
    - on arm64: [qemu-system-arm]
    - qemu-utils
    - libslang2
    organize:
      usr/lib/*/pulseaudio/libpulsecommon-*.so: usr/lib/
      usr/share/seabios/*: qemu/
      usr/lib/ipxe/qemu/*: qemu/

  kvm-support:
    plugin: nil
    override-pull: ""
    stage-packages:
    - try: [msr-tools]

  xterm:
    plugin: nil
    override-pull: ""
    stage-packages:
    - xterm
    stage:
    - -usr/lib/*/libfreetype.so.6
    - -usr/share/doc/libfreetype6/FTL.TXT.gz
    - -usr/share/doc/libfreetype6/TODO
    - -usr/share/doc/libfreetype6/changelog.Debian.gz
    - -usr/share/doc/libfreetype6/pcf/README

  glue:
    plugin: dump
    source: snap-wrappers
